# This file was generated by GoReleaser. DO NOT EDIT.
class Vin < Formula
  desc "Simple baseball CLI."
  homepage "https://github.com/benfb/vin/"
  url "https://github.com/benfb/vin/releases/download/v0.4.0/vin_0.4.0_darwin_amd64.tar.gz"
  version "0.4.0"
  sha256 "4c2ec21636a5135f473a1beb36b1d170fcba2a6aa44352d8031a1cfc8ab661cc"

  def install
    bin.install "vin"
  end
end
